name: Deploy to GitHub Pages
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  dumpenv:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    steps:
      - name: dump env
        run: env
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@main"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "publishconf.py"
      requirements: "pelican[markdown] pymdown-extensions git+https://github.com/DiosDelRayo/pelican-taskstack"

