name: Update Pelican Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Pelican
        run: pip install pelican[markdown] pelican-tag-cloud pymdown-extensions
      
      - name: Build site
        run: pelican content -d -v
      
      - name: Upload artifact
        id: deployment
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./output/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy site
        id: deployment
        uses: actions/deploy-pages@v3
