name: Deploy to GitHub Pages
on:
  issues:
    types:
      - labeled
      - unlabeled
      - deleted
      - closed
      - reopened
  push:
    branches: ["master"]
  workflow_dispatch:
concurrency:
  group: taskstack
  cancel-in-progress: true
jobs:
  deploy:
    uses: "DiosDelRayo/DiosDelRayo.github.io/.github/workflows/github_pages.yml@master"
    with:
      settings: "publishconf.py"
      requirements: "pelican[markdown] pymdown-extensions git+https://github.com/DiosDelRayo/pelican-taskstack"
    secrets:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      issues: read
      contents: "read"
      pages: "write"
      id-token: "write"

