name: Deploy to GitHub Pages
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "DiosDelRayo/DiosDelRayo.github.io/.github/workflows/github_pages.yml@master"
    with:
      ghtoken: ${{ secrets.GITHUB_TOKEN }}
      settings: "publishconf.py"
      requirements: "pelican[markdown] pymdown-extensions git+https://github.com/DiosDelRayo/pelican-taskstack"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"

