name: Deploy to GitHub Pages
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  deploy:
  steps:
    - name: Dump env
      run: env
    - uses: "getpelican/pelican/.github/workflows/github_pages.yml@main"
      permissions:
        contents: "read"
        pages: "write"
        id-token: "write"
      with:
        settings: "publishconf.py"
        requirements: "pelican[markdown] pymdown-extensions git+https://github.com/DiosDelRayo/pelican-taskstack"

