name: Update Pelican Site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Pelican
        run: pip install pelican[markdown] pelican-tag-cloud pymdown-extensions
      - name: Build site
        run: pelican content
      - name: Deploy site
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          build_dir: output
