name: Update Pelican Site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: DiosDelRayo/DiosDelRayo.github.io@master
      - name: Install Pelican
        run: pip install pelican[markdown] pelican-tag-cloud pymdownx
      - name: Build site
        run: pelican content
      - name: Deploy site
        uses: gh-pages/deploy@4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_branch: master
          build_dir: output
